#!/bin/sh
# Regenerate the embedded tilemap (terrain) shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-tilemap-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=tilemap_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

# tilemap_shadow is the depth-only caster the light camera draws the terrain with.
for base in tilemap tilemap_shadow; do
    for s in vert frag; do
        stage=$([ "$s" = vert ] && echo vertex || echo fragment)
        "$SHADERCROSS" "$base.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "$base.$s.spv"
        "$SHADERCROSS" "$base.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "$base.$s.msl"
    done
done

{
    echo "// Generated by build-tilemap-shaders.sh from tilemap{,_shadow}.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_TILEMAP_SHADERS_H"
    echo "#define VISTA_TILEMAP_SHADERS_H"
    echo
    for base in tilemap tilemap_shadow; do
        for s in vert frag; do
            emit "$base.$s.spv" "${base}_${s}_spv"
            emit "$base.$s.msl" "${base}_${s}_msl"
        done
    done
    echo
    echo "#endif // VISTA_TILEMAP_SHADERS_H"
} > "$OUT"

rm -f tilemap.vert.spv tilemap.vert.msl tilemap.frag.spv tilemap.frag.msl \
      tilemap_shadow.vert.spv tilemap_shadow.vert.msl tilemap_shadow.frag.spv tilemap_shadow.frag.msl
echo "Wrote $OUT"
