#!/bin/sh
# Regenerate the embedded water shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-water-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=water_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "water.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "water.$s.spv"
    "$SHADERCROSS" "water.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "water.$s.msl"
done

{
    echo "// Generated by build-water-shaders.sh from water.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_WATER_SHADERS_H"
    echo "#define VISTA_WATER_SHADERS_H"
    echo
    for s in vert frag; do
        emit "water.$s.spv" "water_${s}_spv"
        emit "water.$s.msl" "water_${s}_msl"
    done
    echo
    echo "#endif // VISTA_WATER_SHADERS_H"
} > "$OUT"

rm -f water.vert.spv water.vert.msl water.frag.spv water.frag.msl
echo "Wrote $OUT"
