#!/bin/sh
# Regenerate the embedded 3dx object shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# The vertex shader is compiled twice, mirroring the original's `#if(WEIGHT>1)`:
# a lod that binds one bone per vertex has no weight bytes in its vertex, so its
# layout -- and therefore its shader -- differs from the skinned one.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-object3dx-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=object3dx_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

"$SHADERCROSS" object3dx.vert.hlsl -s HLSL -t vertex -DSKINNED=0 -d SPIRV -o object3dx_rigid.vert.spv
"$SHADERCROSS" object3dx.vert.hlsl -s HLSL -t vertex -DSKINNED=0 -d MSL   -o object3dx_rigid.vert.msl
"$SHADERCROSS" object3dx.vert.hlsl -s HLSL -t vertex -DSKINNED=1 -d SPIRV -o object3dx_skin.vert.spv
"$SHADERCROSS" object3dx.vert.hlsl -s HLSL -t vertex -DSKINNED=1 -d MSL   -o object3dx_skin.vert.msl
"$SHADERCROSS" object3dx.frag.hlsl -s HLSL -t fragment -d SPIRV -o object3dx.frag.spv
"$SHADERCROSS" object3dx.frag.hlsl -s HLSL -t fragment -d MSL   -o object3dx.frag.msl

{
    echo "// Generated by build-object3dx-shaders.sh from object3dx.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "// The _rigid_ vertex blobs are -DSKINNED=0 (one bone, no weight bytes);"
    echo "// the _skin_ ones are -DSKINNED=1 (2..4 weighted bones)."
    echo "#ifndef VISTA_OBJECT3DX_SHADERS_H"
    echo "#define VISTA_OBJECT3DX_SHADERS_H"
    echo
    emit object3dx_rigid.vert.spv object3dx_rigid_vert_spv
    emit object3dx_rigid.vert.msl object3dx_rigid_vert_msl
    emit object3dx_skin.vert.spv  object3dx_skin_vert_spv
    emit object3dx_skin.vert.msl  object3dx_skin_vert_msl
    emit object3dx.frag.spv       object3dx_frag_spv
    emit object3dx.frag.msl       object3dx_frag_msl
    echo
    echo "#endif // VISTA_OBJECT3DX_SHADERS_H"
} > "$OUT"

rm -f object3dx_rigid.vert.spv object3dx_rigid.vert.msl \
      object3dx_skin.vert.spv object3dx_skin.vert.msl \
      object3dx.frag.spv object3dx.frag.msl
echo "Wrote $OUT"
