#!/bin/sh
# Regenerate the embedded water fragment-shader blob from water.frag.hlsl.
# The water pipeline reuses the mesh3d vertex shader (mesh3d_shaders.h), so only
# the fragment stage is compiled here. See build-mesh-shaders.sh for the toolchain.
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=water_shaders.h

"$SHADERCROSS" water.frag.hlsl -s HLSL -t fragment -d SPIRV -o water.frag.spv
"$SHADERCROSS" water.frag.hlsl -s HLSL -t fragment -d MSL   -o water.frag.msl

{
    echo "// Generated by build-water-shaders.sh from water.frag.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\".  Vertex stage: mesh3d_vert_*."
    echo "#ifndef VISTA_WATER_SHADERS_H"
    echo "#define VISTA_WATER_SHADERS_H"
    echo
    xxd -i -n water_frag_spv water.frag.spv
    xxd -i -n water_frag_msl water.frag.msl
    echo
    echo "#endif // VISTA_WATER_SHADERS_H"
} > "$OUT"

rm -f water.frag.spv water.frag.msl
echo "Wrote $OUT"
