#!/bin/sh
# Regenerate the embedded grass shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-grass-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=grass_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "grass.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "grass.$s.spv"
    "$SHADERCROSS" "grass.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "grass.$s.msl"
done

{
    echo "// Generated by build-grass-shaders.sh from grass.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_GRASS_SHADERS_H"
    echo "#define VISTA_GRASS_SHADERS_H"
    echo
    for s in vert frag; do
        emit "grass.$s.spv" "grass_${s}_spv"
        emit "grass.$s.msl" "grass_${s}_msl"
    done
    echo
    echo "#endif // VISTA_GRASS_SHADERS_H"
} > "$OUT"

rm -f grass.vert.spv grass.vert.msl grass.frag.spv grass.frag.msl
echo "Wrote $OUT"
