#!/bin/sh
# Regenerate the embedded coast-sprite shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-coastsprites-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=coastsprites_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "coastsprites.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "coastsprites.$s.spv"
    "$SHADERCROSS" "coastsprites.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "coastsprites.$s.msl"
done

{
    echo "// Generated by build-coastsprites-shaders.sh from coastsprites.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_COASTSPRITES_SHADERS_H"
    echo "#define VISTA_COASTSPRITES_SHADERS_H"
    echo
    for s in vert frag; do
        emit "coastsprites.$s.spv" "coastsprites_${s}_spv"
        emit "coastsprites.$s.msl" "coastsprites_${s}_msl"
    done
    echo
    echo "#endif // VISTA_COASTSPRITES_SHADERS_H"
} > "$OUT"

rm -f coastsprites.vert.spv coastsprites.vert.msl coastsprites.frag.spv coastsprites.frag.msl
echo "Wrote $OUT"
