#!/bin/sh
# Regenerate the embedded minimap shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# One vertex shader (minimap.vert) feeds both fragment shaders: minimap.frag draws the map
# itself, minimap_border.frag everything on top of it.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-minimap-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=minimap_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

compile() { # <basename> <stage>
    stage=$([ "$2" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "$1.$2.hlsl" -s HLSL -t "$stage" -d SPIRV -o "$1.$2.spv"
    "$SHADERCROSS" "$1.$2.hlsl" -s HLSL -t "$stage" -d MSL   -o "$1.$2.msl"
}

compile minimap vert
compile minimap frag
compile minimap_border frag

{
    echo "// Generated by build-minimap-shaders.sh from minimap.{vert,frag}.hlsl and"
    echo "// minimap_border.frag.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_MINIMAP_SHADERS_H"
    echo "#define VISTA_MINIMAP_SHADERS_H"
    echo
    emit minimap.vert.spv        minimap_vert_spv
    emit minimap.vert.msl        minimap_vert_msl
    emit minimap.frag.spv        minimap_frag_spv
    emit minimap.frag.msl        minimap_frag_msl
    emit minimap_border.frag.spv minimap_border_frag_spv
    emit minimap_border.frag.msl minimap_border_frag_msl
    echo
    echo "#endif // VISTA_MINIMAP_SHADERS_H"
} > "$OUT"

rm -f minimap.vert.spv minimap.vert.msl minimap.frag.spv minimap.frag.msl \
      minimap_border.frag.spv minimap_border.frag.msl
echo "Wrote $OUT"
