#!/bin/sh
# Regenerate the embedded tilemap (terrain) shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-tilemap-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=tilemap_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "tilemap.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "tilemap.$s.spv"
    "$SHADERCROSS" "tilemap.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "tilemap.$s.msl"
done

{
    echo "// Generated by build-tilemap-shaders.sh from tilemap.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_TILEMAP_SHADERS_H"
    echo "#define VISTA_TILEMAP_SHADERS_H"
    echo
    emit tilemap.vert.spv tilemap_vert_spv
    emit tilemap.vert.msl tilemap_vert_msl
    emit tilemap.frag.spv tilemap_frag_spv
    emit tilemap.frag.msl tilemap_frag_msl
    echo
    echo "#endif // VISTA_TILEMAP_SHADERS_H"
} > "$OUT"

rm -f tilemap.vert.spv tilemap.vert.msl tilemap.frag.spv tilemap.frag.msl
echo "Wrote $OUT"
