#!/bin/sh
# Regenerate the embedded world-quad shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-worldquad-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=worldquad_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "worldquad.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "worldquad.$s.spv"
    "$SHADERCROSS" "worldquad.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "worldquad.$s.msl"
done

{
    echo "// Generated by build-worldquad-shaders.sh from worldquad.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_WORLDQUAD_SHADERS_H"
    echo "#define VISTA_WORLDQUAD_SHADERS_H"
    echo
    for s in vert frag; do
        emit "worldquad.$s.spv" "worldquad_${s}_spv"
        emit "worldquad.$s.msl" "worldquad_${s}_msl"
    done
    echo
    echo "#endif // VISTA_WORLDQUAD_SHADERS_H"
} > "$OUT"

rm -f worldquad.vert.spv worldquad.vert.msl worldquad.frag.spv worldquad.frag.msl
echo "Wrote $OUT"
