#!/bin/sh
# Regenerate the embedded world-triangle shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-worldtri-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=worldtri_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "worldtri.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "worldtri.$s.spv"
    "$SHADERCROSS" "worldtri.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "worldtri.$s.msl"
done

{
    echo "// Generated by build-worldtri-shaders.sh from worldtri.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_WORLDTRI_SHADERS_H"
    echo "#define VISTA_WORLDTRI_SHADERS_H"
    echo
    for s in vert frag; do
        emit "worldtri.$s.spv" "worldtri_${s}_spv"
        emit "worldtri.$s.msl" "worldtri_${s}_msl"
    done
    echo
    echo "#endif // VISTA_WORLDTRI_SHADERS_H"
} > "$OUT"

rm -f worldtri.vert.spv worldtri.vert.msl worldtri.frag.spv worldtri.frag.msl
echo "Wrote $OUT"
