#!/bin/sh
# Regenerate the embedded cloudshadow shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-cloudshadow-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=cloudshadow_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "cloudshadow.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "cloudshadow.$s.spv"
    "$SHADERCROSS" "cloudshadow.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "cloudshadow.$s.msl"
done

{
    echo "// Generated by build-cloudshadow-shaders.sh from cloudshadow.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_CLOUDSHADOW_SHADERS_H"
    echo "#define VISTA_CLOUDSHADOW_SHADERS_H"
    echo
    for s in vert frag; do
        emit "cloudshadow.$s.spv" "cloudshadow_${s}_spv"
        emit "cloudshadow.$s.msl" "cloudshadow_${s}_msl"
    done
    echo
    echo "#endif // VISTA_CLOUDSHADOW_SHADERS_H"
} > "$OUT"

rm -f cloudshadow.vert.spv cloudshadow.vert.msl cloudshadow.frag.spv cloudshadow.frag.msl
echo "Wrote $OUT"
