#!/bin/sh
# Regenerate the embedded UI shader blobs from the HLSL sources.
#
# Authored in HLSL, cross-compiled to SPIR-V (Vulkan) and MSL (Metal) with
# SDL_shadercross, then embedded as C byte arrays in ui_shaders.h (checked in,
# so the engine build needs no shader compiler).
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=ui_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

# Compile each stage to both backends.
for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "ui.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "ui.$s.spv"
    "$SHADERCROSS" "ui.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "ui.$s.msl"
done

{
    echo "// Generated by build-shaders.sh from ui.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_UI_SHADERS_H"
    echo "#define VISTA_UI_SHADERS_H"
    echo
    emit ui.vert.spv ui_vert_spv
    emit ui.vert.msl ui_vert_msl
    emit ui.frag.spv ui_frag_spv
    emit ui.frag.msl ui_frag_msl
    echo
    echo "#endif // VISTA_UI_SHADERS_H"
} > "$OUT"

rm -f ui.vert.spv ui.vert.msl ui.frag.spv ui.frag.msl
echo "Wrote $OUT"
