#!/bin/sh
# Regenerate the embedded 3dx object shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# The vertex shader is compiled once per (SKINNED, BUMP) pair and the fragment shader
# once per BUMP. SKINNED mirrors the original's `#if(WEIGHT>1)`: a lod that binds one
# bone per vertex has no weight bytes in its vertex, so its layout -- and therefore its
# shader -- differs from the skinned one. BUMP mirrors the original's two vertex shader
# files (object_scene_light.vsl / object_scene_bump.vsl) and its psl BUMP define; a
# bump vertex also carries a tangent frame.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-object3dx-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=object3dx_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

build() { # <stage> <basename> <defines...>
    stage=$1; base=$2; shift 2
    "$SHADERCROSS" "object3dx.$stage.hlsl" -s HLSL \
        -t "$([ "$stage" = vert ] && echo vertex || echo fragment)" \
        "$@" -d SPIRV -o "$base.spv"
    "$SHADERCROSS" "object3dx.$stage.hlsl" -s HLSL \
        -t "$([ "$stage" = vert ] && echo vertex || echo fragment)" \
        "$@" -d MSL -o "$base.msl"
}

build vert object3dx_rigid_vert      -DSKINNED=0 -DBUMP=0
build vert object3dx_skin_vert       -DSKINNED=1 -DBUMP=0
build vert object3dx_rigid_bump_vert -DSKINNED=0 -DBUMP=1
build vert object3dx_skin_bump_vert  -DSKINNED=1 -DBUMP=1
build frag object3dx_frag            -DBUMP=0
build frag object3dx_bump_frag       -DBUMP=1

{
    echo "// Generated by build-object3dx-shaders.sh from object3dx.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "// _rigid_ vertex blobs are -DSKINNED=0 (one bone, no weight bytes); _skin_ ones"
    echo "// are -DSKINNED=1 (2..4 weighted bones). _bump_ blobs are -DBUMP=1."
    echo "#ifndef VISTA_OBJECT3DX_SHADERS_H"
    echo "#define VISTA_OBJECT3DX_SHADERS_H"
    echo
    for b in object3dx_rigid_vert object3dx_skin_vert \
             object3dx_rigid_bump_vert object3dx_skin_bump_vert \
             object3dx_frag object3dx_bump_frag; do
        emit "$b.spv" "${b}_spv"
        emit "$b.msl" "${b}_msl"
    done
    echo
    echo "#endif // VISTA_OBJECT3DX_SHADERS_H"
} > "$OUT"

rm -f object3dx_*_vert.spv object3dx_*_vert.msl object3dx_frag.spv object3dx_frag.msl \
      object3dx_bump_frag.spv object3dx_bump_frag.msl
echo "Wrote $OUT"
