#!/bin/sh
# Regenerate the embedded 3D static-mesh shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-mesh-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=mesh3d_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "mesh3d.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "mesh3d.$s.spv"
    "$SHADERCROSS" "mesh3d.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "mesh3d.$s.msl"
done

{
    echo "// Generated by build-mesh-shaders.sh from mesh3d.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_MESH3D_SHADERS_H"
    echo "#define VISTA_MESH3D_SHADERS_H"
    echo
    emit mesh3d.vert.spv mesh3d_vert_spv
    emit mesh3d.vert.msl mesh3d_vert_msl
    emit mesh3d.frag.spv mesh3d_frag_spv
    emit mesh3d.frag.msl mesh3d_frag_msl
    echo
    echo "#endif // VISTA_MESH3D_SHADERS_H"
} > "$OUT"

rm -f mesh3d.vert.spv mesh3d.vert.msl mesh3d.frag.spv mesh3d.frag.msl
echo "Wrote $OUT"
