#!/bin/sh
# Regenerate the embedded water shader blobs from the HLSL sources.
# See build-shaders.sh for the UI shaders; same toolchain.
#
# Each stage is compiled once per REFLECTION. REFLECTION=0 is the original's
# water_easy.{vsl,psl} (WATER_EMPTY); REFLECTION=1 is water_linear.{vsl,psl}
# (WATER_LINEAR_REFLECTION), which samples the planar-reflection render target and so
# declares a third sampler -- hence separate shader objects, not just separate pipelines.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-water-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=water_shaders.h

emit() { # <file> <c-name>
    xxd -i -n "$2" "$1"
}

build() { # <stage> <basename> <defines...>
    stage=$1; base=$2; shift 2
    t=$([ "$stage" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "water.$stage.hlsl" -s HLSL -t "$t" "$@" -d SPIRV -o "$base.spv"
    "$SHADERCROSS" "water.$stage.hlsl" -s HLSL -t "$t" "$@" -d MSL   -o "$base.msl"
}

build vert water_vert         -DREFLECTION=0
build frag water_frag         -DREFLECTION=0
build vert water_reflect_vert -DREFLECTION=1
build frag water_reflect_frag -DREFLECTION=1

{
    echo "// Generated by build-water-shaders.sh from water.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "// _reflect_ blobs are -DREFLECTION=1 (water_linear, samples the planar-reflection"
    echo "// target); the others -DREFLECTION=0 (water_easy)."
    echo "#ifndef VISTA_WATER_SHADERS_H"
    echo "#define VISTA_WATER_SHADERS_H"
    echo
    for b in water_vert water_frag water_reflect_vert water_reflect_frag; do
        emit "$b.spv" "${b}_spv"
        emit "$b.msl" "${b}_msl"
    done
    echo
    echo "#endif // VISTA_WATER_SHADERS_H"
} > "$OUT"

rm -f water_vert.spv water_vert.msl water_frag.spv water_frag.msl \
      water_reflect_vert.spv water_reflect_vert.msl \
      water_reflect_frag.spv water_reflect_frag.msl
echo "Wrote $OUT"
