#!/bin/sh
# Regenerate the embedded coast-foam shader blobs from foam.{vert,frag}.hlsl.
# Foam has its own vertex format (pos/color/uv, stride 24), so both stages are
# compiled here. See build-mesh-shaders.sh for the toolchain.
#
# Usage:  SHADERCROSS=/path/to/shadercross ./build-foam-shaders.sh
set -e
cd "$(dirname "$0")"

SHADERCROSS="${SHADERCROSS:-shadercross}"
OUT=foam_shaders.h

for s in vert frag; do
    stage=$([ "$s" = vert ] && echo vertex || echo fragment)
    "$SHADERCROSS" "foam.$s.hlsl" -s HLSL -t "$stage" -d SPIRV -o "foam.$s.spv"
    "$SHADERCROSS" "foam.$s.hlsl" -s HLSL -t "$stage" -d MSL   -o "foam.$s.msl"
done

{
    echo "// Generated by build-foam-shaders.sh from foam.{vert,frag}.hlsl — do not edit."
    echo "// SPIR-V entrypoint: \"main\".  MSL entrypoint: \"main0\"."
    echo "#ifndef VISTA_FOAM_SHADERS_H"
    echo "#define VISTA_FOAM_SHADERS_H"
    echo
    xxd -i -n foam_vert_spv foam.vert.spv
    xxd -i -n foam_vert_msl foam.vert.msl
    xxd -i -n foam_frag_spv foam.frag.spv
    xxd -i -n foam_frag_msl foam.frag.msl
    echo
    echo "#endif // VISTA_FOAM_SHADERS_H"
} > "$OUT"

rm -f foam.vert.spv foam.vert.msl foam.frag.spv foam.frag.msl
echo "Wrote $OUT"
