//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SurMap5.rc
//
#define ID_SAVE                         2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_BARDLG_GEO                  102
#define IDS_TIME_ELAPSED_LOAD_LANGUAGE  102
#define IDD_BARDLG_TOOLZER              103
#define IDS_LANGUAGE_FILE_VERSION       103
#define IDR_HTML_DLGSELECTWORLD         104
#define IDS_CODEPAGE_NUMS               104
#define IDS_ID_COLUMN_HEADER            105
#define IDS_STATUS_SAVE_LANGUAGE        105
#define CG_IDS_PROGRESS_CAPTION         106
#define IDS_STATUS_LOAD_LANGUAGE        107
#define CG_IDD_PROGRESS                 108
#define IDS_TIME_LEFT_LOAD_LANGUAGE     108
#define IDS_IMPORT_XLS_FILE             109
#define IDS_EXPORT_XLS_FILE             110
#define IDR_MAINFRAME                   128
#define IDR_SurMap5TYPE                 129
#define ID_COMBO                        129
#define IDS_APPLY_BUTTON                130
#define IDC_NODROP                      130
#define IDR_LIBRARIES_EXTERNAL_BAR      130
#define IDR_POPUP_TREE                  131
#define IDS_CANCEL_BUTTON               131
#define IDC_POINTER_COPY                131
#define IDR_EDITORS_BAR                 131
#define IDB_BTMP_FORM_BRUSH             132
#define IDS_ERROR_IN_CUSTOM_VALUE       132
#define IDS_NAME_COLUMN                 133
#define IDS_VALUE_COLUMN                134
#define IDD_BARDLG_HARDNESS             135
#define IDS_REMOVE_ITEM                 135
#define IDD_BARDLG_KIND                 135
#define IDD_BARDLG_COLORPIC             136
#define IDS_PANE_TEXT                   136
#define ID_FILE_EXIT                    137
#define IDC_FPOINT                      140
#define IDB_HDRUP                       141
#define IDC_POINTER                     141
#define IDB_HDRDOWN                     142
#define IDC_SPLITTER                    142
#define IDD_DLG_SELECTWORLD             143
#define IDD_DLG_WORLDNAME               144
#define IDB_ATTRIB_EDITOR_CTRL          146
#define IDD_DLG_CREATE_UNIT             146
#define IDD_DLG_CAMERA                  149
#define IDD_DLG_ENTERNAME               150
#define IDD_DLG_SELECTTRIGGER           152
#define IDB_TREETOOLDLG_BITMAP          155
#define IDD_DLG_FILE_PROPERTIES         156
#define IDD_MINIMAP_DLG                 159
#define IDD_BARDLG_MINIMAP              159
#define IDB_MAINFRAME_TOOLBAR256_EXTERNAL 164
#define IDB_MAINFRAME_TOOLBAREXTERNAL256 165
#define IDB_TREETOOLDLG_BITMAP256       167
#define IDD_BARDLG_IMP                  168
#define IDD_BARDLG_GEOTX                169
#define IDD_BARDLG_3DM                  173
#define IDD_BARDLG_ROAD                 175
#define IDR_MENU1                       180
#define IDD_COMBO_NAME_DLG              182
#define IDD_DLG_NAME_COMBO              182
#define IDB_CONDITION_CORNER            183
#define IDD_DLG_CHANGE_WORLD_HEIGHT     185
#define IDR_TOOLBAR1                    187
#define IDR_MAINFRAME_256               187
#define IDD_BARDLG_BLUR                 189
#define IDR_LIBRARIES_BAR               189
#define IDD_BARDLG_GEONET               190
#define IDR_FILTERS_BAR                 190
#define IDD_BARDLG_EMPTY                191
#define IDR_MAINFRAME_EXTERNAL          191
#define IDD_BARDLG_WATER                192
#define IDD_BARDLG_WATERSRC             192
#define IDR_MAINFRAME_EXTERNAL2         192
#define IDR_EDITORS_EXTERNAL_BAR        192
#define IDR_TOOLBAR2                    193
#define IDR_TOOLS_BAR                   193
#define IDR_TOOLS_BAR1                  194
#define IDR_WORKSPACE_BAR               194
#define IDD_BARDLG_UNIT                 195
#define IDD_BARDLG_UNITFOLDER           196
#define IDD_BARDLG_PLAYERFOLDER         197
#define IDR_FILTERS_EXTERNAL_BAR        198
#define IDD_BARDLG_CAMERA               201
#define IDD_BARDLG_ICE                  203
#define IDD_BARDLG_WAVES                206
#define IDD_DLG_WAVE                    207
#define IDD_BARDLG_WINDSRC1             208
#define IDD_BARDLG_WINDSTATIC           208
#define IDD_BARDLG_GRASS                209
#define IDD_BARDLG_DETAILE              210
#define IDD_OUTPUT_PROGRESS             215
#define IDB_SPLASH                      217
#define IDD_DLG_EXIMWORLD               218
#define IDD_PROGRESSDIALOG              219
#define IDD_BARDLG_MINIDETAILE_FOLDER   220
#define IDI_ICON1                       221
#define IDI_WORLD                       221
#define IDD_DLG_BORDER_ROLLING          222
#define IDB_BITMAP1                     223
#define IDD_BARDLG_SPECFILTER           225
#define IDC_TREE_CTRL                   1000
#define IDC_ATTRIB_EDITOR               1000
#define CG_IDC_PROGTIME_ELAPSED         1000
#define IDC_HORIZONTAL_LINE             1001
#define CG_IDC_PROGTIME_LEFT            1001
#define IDC_COORD_LEFT_EDIT             1002
#define CG_IDC_PROGDLG_PROGRESS         1002
#define IDC_RADIO1                      1003
#define IDC_RDB_LEVELING_1              1003
#define IDC_COORD_TOP_EDIT              1003
#define CG_IDC_PROGDLG_PERCENT          1003
#define IDC_FULL_EXPORT                 1003
#define IDCRB_UP_DOWN_1                 1003
#define IDC_RDB_LEVELING_2_ZL_OR_LEVELING_H_2 1004
#define IDC_RDB_LEVELING_2              1004
#define IDC_COORD_WIDTH_EDIT            1004
#define IDC_BUTTON_STOP                 1004
#define IDCRB_UP_DOWN_2                 1004
#define IDC_BUTTON1                     1005
#define IDC_COORD_HEIGHT_EDIT           1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_EDIT1                       1006
#define IDC_EDITRADIUS                  1006
#define IDC_ANGLE_MORE_BUTTON           1006
#define IDC_NEXT_BUTTON                 1006
#define IDC_VIEW                        1006
#define IDC_REMOVE_WAVE                 1006
#define IDC_DELETE_BUTTON               1006
#define IDC_LEFT_MORE_BUTTON            1006
#define IDC_COORD_LABEL                 1007
#define IDC_ADD_POINT                   1007
#define IDC_RIGHT_LESS_BUTTON           1007
#define IDCRB_RELATIVE_ABS_1            1007
#define IDC_SLIDER1                     1008
#define IDC_SLIDER_EDITRADIUS           1008
#define IDC_COORD_COMMA_LABEL           1008
#define IDC_REMOVE_POINT                1008
#define IDC_RIGHT_MORE_BUTTON           1008
#define IDCRB_RELATIVE_ABS_2            1008
#define IDC_SLIDER_EDITDELTAH           1009
#define IDC_COORD_X_LABEL               1009
#define IDCRB_PUT_DIG_1                 1009
#define IDC_LOWER_LINE                  1010
#define IDC_SATURATION_EDIT             1010
#define IDCRB_PUT_DIG_2                 1010
#define IDC_UPPER_LINE                  1011
#define IDC_V_LINE                      1011
#define IDC_EDITDELTAH                  1012
#define IDC_TEXTURE_ADD_BUTTON          1012
#define IDC_RADIO_DIGPUT1               1013
#define IDC_TEXTURES_COMBO              1013
#define IDC_RADIO_DIGPUT2               1014
#define IDC_TEXTURE_SIZE_LABEL          1014
#define IDC_COMBOBOXEX_TOOLZERFORM      1015
#define IDC_TEXTURE_REMOVE_BUTTON       1015
#define IDR_MAINFRAME1                  1015
#define IDC_SLIDER_TOOLZERFRONTFORM     1016
#define IDC_GRADIENT_EDITOR             1016
#define IDC_H_LINE1                     1016
#define IDC_RADIO_CIRCLEQUAD1           1017
#define IDC_R_SLIDER                    1017
#define IDC_H_LINE2                     1017
#define IDC_RADIO_CIRCLEQUAD2           1018
#define IDC_G_SLIDER                    1018
#define IDC_H_LINE3                     1018
#define IDC_SLDR_EDT_LEVELING_H         1019
#define IDC_A_SLIDER                    1019
#define IDC_TEXTURE_LOC_ADD_BUTTON      1019
#define IDC_EDT_LEVELING_H              1020
#define IDC_B_SLIDER                    1020
#define IDC_EDT_DELTALEVELING_H2O       1021
#define IDC_SLDR_EDT_DELTALEVELING_H2O  1022
#define IDC_R_EDIT                      1022
#define IDC_RDB_INSERTDELETE_SOURCE1    1023
#define IDC_G_EDIT                      1023
#define IDC_RDB_INSERTDELETE_SOURCE2    1024
#define IDC_B_EDIT                      1024
#define IDC_TABLEPATH_EDIT              1025
#define IDC_A_EDIT                      1025
#define IDC_TAB_OBJECTS                 1025
#define IDC_READ_BUTTON                 1026
#define IDC_SOLID_COLOR                 1026
#define IDC_BTN_BROWSE_FILE             1027
#define IDC_POSITION_EDIT               1027
#define IDC_EDT_MODEL                   1028
#define IDC_BTN_BROWSE_FILEV            1028
#define IDC_BTN_BROWSE_FILE2            1028
#define IDC_BTN_TURNZ_LESS              1029
#define IDC_BTN_BROWSE_FILE_EDGEBITMAP_TEXTURE 1029
#define IDC_BTN_SCALINGXYZ_LESS         1030
#define IDC_SCALE_LESS_BUTTON           1030
#define IDC_BTN_BROWSE_FILE_EDGE        1030
#define IDC_BTN_BROWSE_FILE_EDGEBITMAP_VTEXTURE 1030
#define IDC_BTN_TURNZ_BIGGLE            1031
#define IDC_BTN_TURNZ_BIGGER            1031
#define IDC_BTN_SCALINGXYZ_BIGGER       1032
#define IDC_EDT_BITMAP                  1032
#define IDC_SCALE_MORE_BUTTON           1032
#define IDC_BTN_BROWSE_BITMAP           1033
#define IDC_RADIUS_LESS_BUTTON          1033
#define IDC_EDT_BITMAPV                 1033
#define IDC_EDIT_WORLDSIZE_X            1034
#define IDC_RADIUS_MORE_BUTTON          1034
#define IDC_EDT_EDGEBITMAP_TEXTURE      1034
#define IDC_BACKGROUND_COLOR            1034
#define IDC_EDIT_WORLDSIZE_Y            1035
#define IDC_D_RADIUS_LESS_BUTTON        1035
#define IDC_EDT_EDGEBITMAP_VTEXTURE     1035
#define IDC_SATURATION_SLIDER           1035
#define IDC_EDIT_WORLDHEIGH             1036
#define IDC_D_RADIUS_MORE_BUTTON        1036
#define IDC_DIFFUSE_COLOR               1036
#define IDC_EDIT_N                      1037
#define IDC_LST_WORLD                   1037
#define IDC_DIFFUSE_COLOR_LABEL         1037
#define IDC_SPIN_N                      1038
#define IDC_BTN_NEWWORLD                1038
#define IDC_SATURATION_LABEL            1038
#define IDC_EDIT_PHASE                  1039
#define IDC_EDT_WORLDNAME               1039
#define IDC_BTN_NEWWORLD2               1039
#define IDC_BTN_DELETEWORLD             1039
#define IDC_TEXTURE_LABEL               1039
#define IDC_SPIN_PHASE                  1040
#define IDC_UNIT_TREE                   1040
#define IDC_CHECK_PHASERND              1041
#define IDC_D_ANGLE_LESS_BUTTON         1041
#define IDC_WEAPON_TREE                 1041
#define IDC_EDIT_WIDTH                  1042
#define IDC_D_ANGLE_MORE_BUTTON         1042
#define IDC_SLIDER_WIDTH                1043
#define IDC_D_SCALE_LESS_BUTTON         1043
#define IDC_CHECK_SYNC                  1044
#define IDC_ATTRIB_EDITOR_CTRL          1044
#define IDC_D_SCALE_MORE_BUTTON         1044
#define IDC_EDIT_HEIGHT                 1045
#define IDC_TYPE_TABS                   1045
#define IDC_SLIDER_HEIGHT               1046
#define IDC_COMBO1                      1046
#define IDC_ATTRIBUTES                  1046
#define IDC_CBOX_ATTRIBUTES             1046
#define IDC_EFFECT_COMBO                1046
#define IDC_LARGE_ATTRIBUTE_EDITOR_CTRL 1046
#define IDC_PARAM_EDITOR_CTRL           1046
#define IDC_NAME_COMBO                  1046
#define IDC_CMB_TEXTURING_METHOD        1046
#define IDC_GRASS_LIST                  1046
#define IDC_EDIT_GNOISE                 1047
#define IDC_CBOXEX_TOOLZERTYPE          1047
#define IDC_CMB_PUT_METHOD              1047
#define IDC_EDIT_MESH                   1048
#define IDC_CHECK_SYNCSCALINGXYZ        1048
#define IDC_CHECK_INVERSE               1048
#define IDC_EDT_ROUGHNESS               1048
#define IDC_OBJECTS_TREE                1048
#define IDC_CHECK_INVERSE2              1049
#define IDC_SLIDER2                     1049
#define IDC_SLDR_ROUGHNESS              1049
#define IDC_SLIDER_R_WIND               1049
#define IDC_ZOOM_SLIDER                 1049
#define IDC_ANGLE_SLIDER                1050
#define IDC_EDIT_H                      1051
#define IDC_ANGLE_EDIT                  1051
#define IDC_SLIDER_H                    1052
#define IDC_ANGLE_LESS_BUTTON           1052
#define IDC_NAME_EDIT                   1054
#define IDC_EFFECTS_COUNT_EDIT          1054
#define IDC_CHAIN_ID_COMBO              1055
#define IDC_ANGLE_LESS_BUTTON2          1055
#define IDC_EDT_CENTERALPHA             1056
#define IDC_EDIT_SCALINGZ               1057
#define IDC_STATIC_POLIGON              1057
#define IDC_SLDR_CENTERALPHA            1057
#define IDC_SLIDER_SCALINGZ             1058
#define IDC_STATIC_POLIGON1             1058
#define IDC_EDT_KCOLOR                  1058
#define IDC_STATIC_POLIGON2             1059
#define IDCSL_ABS_H                     1059
#define IDC_SLD_KCOLOR                  1059
#define IDCSLE_ABS_H                    1060
#define IDC_EDT_SATURATION              1060
#define IDC_SLIDER_TURNZ                1061
#define IDC_SLD_SATURATION              1061
#define IDC_EDIT_TURNZ                  1062
#define IDC_EDT_BRIGHTNESS              1062
#define IDC_SLIDER_SCALINGXYZ           1063
#define IDC_SCALE_SLIDER                1063
#define IDC_SLD_BRIGHTNESS              1063
#define IDC_EDIT_TURNZ2                 1064
#define IDC_EDIT_SCALINGXYZ             1064
#define IDC_SCALE_EDIT                  1064
#define IDC_RADIUS_SLIDER               1065
#define IDC_EDIT_SCALINGY               1066
#define IDC_BUTTON2                     1066
#define IDC_SLIDER_SCALINGY             1067
#define IDC_BUTTON3                     1067
#define IDC_SLIDER_TURNY                1068
#define IDC_BUTTON4                     1068
#define IDC_EDIT_TURNY                  1069
#define IDC_BUTTON5                     1069
#define IDC_EDIT_SCALINGX               1070
#define IDC_BUTTON6                     1070
#define IDC_SLIDER_SCALINGX             1071
#define IDC_LIST1                       1071
#define IDC_SLIDER_TURNX                1072
#define IDC_EDIT2                       1072
#define IDC_EDIT_TURNX                  1073
#define IDC_CHECK1                      1073
#define IDC_SPEED                       1073
#define IDC_CHECK_SYNCSCALINGXY         1074
#define IDC_BUTTON7                     1074
#define IDC_Y_AXIS_CHECK                1074
#define IDC_GENERATION_TIME             1074
#define IDC_EDT_GEOTX                   1075
#define IDC_RADIUS_EDIT                 1075
#define IDC_Z_AXIS_CHECK                1075
#define IDC_D_RADIUS_SLIDER             1076
#define IDC_EDT_GEOTX2                  1076
#define IDC_SIDEUPDOWN1                 1077
#define IDC_DEFAULT_BUTTON              1077
#define IDC_SIDEUPDOWN2                 1078
#define IDC_FORMATIONS_TREE             1078
#define IDC_BUT_PUTSHAPE3D              1079
#define IDC_RBUT_DRAWERASE1             1079
#define IDC_D_RADIUS_EDIT               1079
#define IDC_COMBO_MODELSHAPE3D          1080
#define IDC_RBUT_DRAWERASE2             1080
#define IDCCH_ENABLE_ABS_H              1080
#define IDC_BTN_NEWTRIGGER              1081
#define IDC_BTN_DELETETRIGGER           1082
#define IDC_LST_TRIGGER                 1083
#define IDC_PASTE_CHECK                 1084
#define IDC_MAP_SIZE_EDIT               1085
#define IDC_D_ANGLE_SLIDER              1085
#define IDC_D_ANGLE_EDIT                1086
#define IDC_MINIMAP_WINDOW              1087
#define IDC_D_SCALE_SLIDER              1087
#define IDC_D_SCALE_EDIT                1088
#define IDC_CYCLED_CHECK                1089
#define IDC_PEG_LABEL                   1090
#define IDC_PREV_BUTTON                 1091
#define IDC_BUTTON_LIGHT                1092
#define IDC_FILE_LIST                   1093
#define IDC_HLINE                       1094
#define IDC_ADD_BUTTON                  1095
#define IDC_RENAME_BUTTON               1096
#define IDC_REMOVE_BUTTON               1097
#define IDC_SPREAD_CHECK                1098
#define IDC_CHECK2                      1099
#define IDC_VERTICAL_CHECK              1099
#define IDC_DETAIL_ERACE                1099
#define IDC_DETAIL_ERACE_ALL            1099
#define IDC_INVERT                      1099
#define IDC_CHECK_ENABLE_H_FILTER       1099
#define IDC_SLIDER_BLUR_INTENSITY       1103
#define IDC_SLIDER_CELLPOWER            1104
#define IDC_SLIDER_SHIFTCELLPOWER       1105
#define IDC_SLIDER_BORDERFORM           1106
#define IDC_BUT_RESETSHAPE3D            1107
#define IDC_SLIDER_QUALITY              1108
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY1 1110
#define IDC_DENSITY_EDIT                1110
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY2 1111
#define IDC_DENSITY_LESS_BUTTON         1111
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY3 1112
#define IDC_DENSITY_MORE_BUTTON         1112
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY4 1113
#define IDC_DENSITY_SLIDER              1113
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY5 1114
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY6 1115
#define IDC_MODE_LABEL                  1115
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY7 1116
#define IDC_HINT_LABEL                  1116
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY8 1117
#define IDC_FORMATION_EDITOR            1117
#define IDC_D_DENSITY_SLIDER            1118
#define IDC_H_LINE                      1118
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY9 1118
#define IDC_D_DENSITY_EDIT              1119
#define IDC_TYPES_BUTTON                1119
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY10 1119
#define IDC_D_DENSITY_LESS_BUTTON       1120
#define IDC_BTN_PUTTRACK                1120
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY11 1120
#define IDC_D_DENSITY_MORE_BUTTON       1121
#define IDC_BTN_CLEARROAD               1121
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY12 1121
#define IDC_SLDR_EDT_ROADWIDTH          1122
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY13 1122
#define IDC_EDT_ROADWIDTH               1123
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY14 1123
#define IDC_CHECK_WIND                  1124
#define IDC_FORMULA_EDIT                1124
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY15 1124
#define IDC_EDIT_WINDZ                  1125
#define IDC_RESULT_LABEL                1125
#define IDC_RDB_INSDELHARDNESS_SETSURKIND_INSDELIMPASSABILITY16 1125
#define IDC_STATIC_WIND                 1126
#define IDC_INSERT_BUTTON               1126
#define IDC_SLDR_EDT_EDGEWIDTH          1127
#define IDC_SLDR_EDT_EDGEANGLE          1127
#define IDC_EDT_EDGEWIDTH               1128
#define IDC_EDT_EDGEANGLE               1128
#define IDC_SLDR_EDT_SPHERIC_H          1129
#define IDC_EDT_SPHERIC_H               1130
#define IDC_RD_ROADMETOD1               1131
#define IDC_RD_ROADMETOD2               1132
#define IDC_RD_ROADMETOD3               1133
#define IDC_RD_ROADMETOD4               1134
#define IDC_CH_CLEAR_WIND               1135
#define IDC_CONDITION_LIST              1137
#define IDC_EDT_MINITX                  1138
#define IDC_MINI_DETAIL_ERACE           1139
#define IDC_LAYER_NOT_SUPPORT           1140
#define IDC_TO_LIBRARY_BUTTON           1141
#define IDC_EXPORT_BUTTON               1142
#define IDC_STATUS_LABEL                1143
#define IDC_IMPORT_BUTTON               1144
#define IDC_TREE_FRAME                  1145
#define IDC_SPLITTER_WINDOW_FRAME       1145
#define IDC_ATTRIB_EDITOR_FRAME         1146
#define IDC_HISTOGRAM_WORLD_INPUT       1147
#define IDC_HISTOGRAM_WORLD_OUTPUT      1148
#define IDC_EDT_INPUT_MAX_HEIGHT        1149
#define IDC_EDT_INPUT_MIN_HEIGHT        1150
#define IDC_EDT_OUT_MAX_HEIGHT          1151
#define IDC_EDT_OUT_MIN_HEIGHT          1152
#define IDC_SLDR_DELTA_H                1153
#define IDC_SLDR_EDT_SCALE_H            1155
#define IDC_SLDR_SCALE_H                1155
#define IDC_EDT_SCALE_H                 1156
#define IDC_EDT_DELTA_H                 1157
#define IDC_SOURCE_TYPE_LABEL           1158
#define IDC_TYPE_LABEL                  1158
#define IDC_X_AXIS_CHECK                1162
#define IDC_TO_SURFACE_LEVEL_BUTTON     1163
#define IDC_TO_SURFACE_NORMAL_BUTTON    1164
#define IDC_SPEED_EDIT                  1165
#define IDC_SPEED_LABEL                 1166
#define IDC_TOTAL_OBJ                   1173
#define IDC_TOTAL_TEXTURES              1175
#define IDC_VERTEX_SIZE                 1177
#define IDC_UNIQE_OBJ                   1183
#define IDC_TOTAL_TEXTURES_SIZE         1184
#define IDC_OBJECTS_LIST                1185
#define IDC_TEXTURES_LIST               1186
#define IDC_ONLY_VISIBLE_OBJECTS        1187
#define IDC_NUM_TEXTURES                1188
#define IDC_SIZE_TEXTURES               1189
#define IDC_ALL_TEXTURES                1190
#define IDC_CREATE_WAVE                 1206
#define IDC_TEXTURE_NAME                1207
#define IDC_SELECT_TEXTURE              1208
#define IDC_LIST_WAVE_LINES             1209
#define IDC_DISTANCE                    1210
#define IDC_APPLY                       1211
#define IDC_SCALE                       1212
#define IDC_FILTER_EDIT                 1213
#define IDC_SCALE2                      1213
#define IDC_ROTATE_CCW_BUTTON           1215
#define IDC_TREE_CONTROL                1216
#define IDC_FILTER_LABEL                1217
#define IDC_EX_XLS_BUTTON               1218
#define IDC_CBOX_PLACEMETOD             1219
#define IDC_STATIC_LINE2                1220
#define IDC_IPADDRESS1                  1221
#define IDC_STATIC_LINE3                1221
#define IDC_STATIC_LINE4                1222
#define IDC_STATIC_LINE5                1223
#define IDC_LIST_                       1224
#define IDC_SIMPLY_LIST                 1224
#define IDC_KEY_LABEL                   1225
#define IDC_BACK_BUTTON                 1226
#define IDC_ADD_TO_LIBRARY_BUTTON       1227
#define IDC_SELECTED_INFO_LABEL         1228
#define IDC_CREATE_LABEL                1230
#define IDC_MODEL_NAME_LABEL            1231
#define IDC_TIME_SLIDER                 1232
#define IDC_TIME_EDIT                   1233
#define IDC_ERASE                       1234
#define IDC_SLIDER_DENSITY              1235
#define IDC_STATIC_DENSITY              1236
#define IDC_RANDOM_SEL_BUTTON           1237
#define IDC_RANDOM_SEL_PERCENT_EDIT     1238
#define IDC_RANDOM_SEL_PERCENT_LABEL    1239
#define IDC_EDIT_BUTTON                 1240
#define IDC_PLAY_CAMERA_BUTTON          1241
#define IDC_VIEW_TO_POINT_BUTTON        1242
#define IDC_POINT_TO_VIEW_BUTTON        1243
#define IDC_SLIDER_INTENSITY            1244
#define IDC_SLIDER_INTENSITY2           1245
#define IDC_BOTTOM                      1246
#define IDC_TOPGRASS                    1247
#define IDC_DONE_BUTTON                 1248
#define IDC_LABEL                       1249
#define IDC_NEXT_POINT_BUTTON           1250
#define IDC_PREV_POINT_BUTTON           1251
#define IDC_POINT_LABEL                 1252
#define IDC_NEXT_FRAME                  1253
#define IDC_PREV_FRAME                  1254
#define IDC_PLAY_CHECK                  1255
#define IDC_DATETIMEPICKER1             1256
#define IDC_BTN_COPY_TRIGGER            1257
#define IDC_RESULTS_TREE                1258
#define IDC_PROGRESS                    1260
#define IDC_MARK_FIRST                  1262
#define IDC_MARK_SECOND                 1263
#define IDC_MARK_THIRD                  1264
#define IDC_MARK_FOURTH                 1265
#define IDC_LEFT_LESS_BUTTON            1266
#define IDC_BOTTOM_MORE_BUTTON          1267
#define IDC_BOTTOM_LESS_BUTTON          1268
#define IDC_TOP_MORE_BUTTON             1269
#define IDC_TOP_LESS_BUTTON             1270
#define IDC_SLD_MINH                    1271
#define IDC_SLD_MAXH                    1272
#define IDC_EDT_TURNX                   1273
#define IDC_EDT_MINH                    1273
#define IDC_EDT_MAXH                    1274
#define IDC_A_LABEL                     1275
#define IDC_SHOW_TYPE_NAMES             1276
#define IDC_CAMERA_RESTRICTION_CHECK    1277
#define IDC_OWN_CAMERA_RESTRICTION_CHECK 1277
#define IDC_ORIGIN_TO_VIEW_BUTTON       1278
#define IDC_BTN_RENAME                  1279
#define IDC_FILE_PROGRESS               1280
#define IDC_TOTAL_PROGRESS              1281
#define IDC_FILENAME_LABEL              1282
#define IDC_TOTAL_LABEL                 1283
#define IDC_FILE_LABEL                  1284
#define IDC_CURRENT_LABEL               1285
#define IDC_COMMANDS_TREE               1286
#define IDC_COMMAND_EDITOR              1287
#define IDC_COMMAND_CUSTOM              1289
#define IDC_BTN_EXPORT                  1291
#define IDC_BTN_IMPORT                  1292
#define IDC_RADIO3                      1296
#define IDC_PARTIAL_EXPORT              1296
#define IDC_EXPORT_OPTIONS              1297
#define IDC_WORLD_NAME_LABEL            1298
#define IDC_HEIGHT_LIMIT_CHECK          1299
#define IDC_LIMIT_HEIGHT_CHECK          1299
#define IDC_LEVELING_LABEL              1300
#define IDC_COLORTERRAINTYPE            1301
#define IDCBTN_PUT2ALLWORLD             1302
#define IDCSLE_ALPHAROAD                1303
#define IDCSL_ALPHAROAD                 1304
#define IDCSLE_ALPHAROADSIDE            1305
#define IDCE_H                          1305
#define IDCSL_ALPHAROADSIDE             1306
#define IDCE_ANGLE                      1306
#define IDCCB_ROAD_MINIDETAIL           1307
#define IDCCB_EDGE_MINIDETAIL           1308
#define IDC_BTN_COLOR                   1308
#define IDC_EDT_MAXDH                   1309
#define IDC_SLD_MAXDH                   1310
#define IDC_EDT_KDETAIL                 1311
#define IDC_SLD_KDETAIL                 1312
#define IDC_EDT_BALANSH                 1313
#define IDC_SLD_BALANSH                 1314
#define IDC_EDT_KUNBRIGHTNESS           1315
#define IDC_SLD_KUNBRIGHTNESS           1316
#define IDC_CONDITION_EDITOR            2001
#define IDD_BARDLG_SOURCE               2018
#define IDD_BARDLG_EDITABLE             2018
#define IDD_BARDLG_PATHEDITOR           2019
#define IDD_BARDLG_SELECT               2020
#define IDD_BARDLG_TRANSFORM            2021
#define IDD_BARDLG_PATHEDITOR1          2024
#define IDD_BARDLG_ENVIRONMENT_EDITOR   2024
#define IDD_TIME_SLIDER                 2025
#define IDD_BARDLG_CAMERA_RESTRICTION   2026
#define IDB_TREELIST_BITMAP             8000
#define IDC_CURSOR_SIZE                 8002
#define IDB_TREELIST_CHECK              8003
#define IDB_TREELIST_LOCK               8004
#define IDC_CURSOR_BUTTON               8005
#define IDC_CURSOR_CHECK                8006
#define IDC_CURSOR_LOCK                 8007
#define IDB_TREELIST_TREE               8008
#define IDB_TREELIST_SORT               8009
#define IDB_TREELIST_HEADER             8010
#define IDB_TREELIST_DISABLE            8011
#define IDC_CURSOR_VERT                 8012
#define IDB_CONDITION_CORNER_NOT        8012
#define IDC_CURSOR_HORZ                 8013
#define IDB_UNIT_EDITOR_TREE            8013
#define IDC_CURSOR_CROSS                8014
#define IDC_CURSOR_DROP                 8015
#define IDC_CURSOR_STOP                 8016
#define IDC_CURSOR_SPLIT                8017
#define ID_VIEW_TREE_BAR                32773
#define ID_VIEW_DLGBAR                  32774
#define IDC_INSERT_BEFORE               32775
#define IDC_REMOVE                      32776
#define ID_DD                           32777
#define ID_VIEW_MINIMAP                 32778
#define IDC_EXTENSIBLE_NODE_ADD_ELEMENT 32779
#define ID_CLEAR_POLYMORFIC             32780
#define ID_POPUP_CREATEFOLDER           32781
#define ID_POPUP_CREATEGEONET           32782
#define ID_CHOOSE_COLOR                 32782
#define ID_POPUP_CREATEBLUR             32783
#define ID_POPUP_CREATEIMP              32784
#define ID_COLLAPSE_ALL_SUBITEMS        32784
#define ID_POPUP_CREATETOOLZER          32785
#define ID_EXPAND_ALL_SUBITEMS          32785
#define ID_POPUP_CREATE3DM              32786
#define ID_POPUP_DELETE                 32787
#define ID_BRUSH_COMBO_PLACE            32791
#define ID_BUTTON_FREE_PLACE2           32792
#define ID_VIEW_ANIMATION               32795
#define ID_FILE_SAVEAS                  32796
#define ID_EDIT_PLAYPMO                 32797
#define ID_POPUP_CREATESOUND            32798
#define ID_TOOLS_EDIT                   32799
#define ID_EDIT_SOUNDS                  32800
#define ID_Menu32801                    32801
#define ID_DEBUG_FILLIN                 32804
#define ID_EDIT_MAPSCENARIO             32805
#define ID_EDIT_WORLDSCENARIO           32806
#define ID_EDIT_TRIGGERS                32807
#define ID_EDIT_UNITS                   32808
#define ID_POPUP_CREATEHARDNESS         32816
#define ID_POPUP_CREATEWATERSRC         32818
#define ID_POPUP_CREATEWATER            32819
#define ID_VIEW_EXTENDEDMODETREELBAR    32820
#define ID_DEBUG_SAVECONFIG             32821
#define ID_POPUP_CREATECOLORPIC         32823
#define ID_POPUP_CREATE3DMONWORLD       32825
#define ID_POPUP_ADDM3D                 32827
#define ID_POP_ADD_M3D_2W               32830
#define ID_POP                          32831
#define ID_FILE_GENERATE                32836
#define ID_EDIT_UNIT_TREE               32837
#define ID_POPUP_CREATEBUBLESRC         32839
#define ID_EDIT_USER_INTERFACE          32840
#define ID_EDIT_OBJECTS                 32842
#define IDM_REMOVE_ELEMENT              32846
#define IDM_ADD_ELEMENT                 32848
#define IDM_CLEAR_CONTAINER             32849
#define IDM_ADD_ELEMENT_COPY            32852
#define IDM_INSERT_ELEMENT_BEFORE       32854
#define ID_VIEW_RESETTOOLBAR2DEFAULT    32855
#define ID_VIEW_BUBBLESOURCE            32868
#define ID_VIEW_WINDSOURCE              32869
#define ID_VIEW_LIGHTSOURCE             32870
#define ID_VIEW_SOURCES                 32871
#define ID_POPUP_CREATEGEOTX            32872
#define ID_FILE_SAVEMINIMAPTOWORLD      32873
#define ID_POPUP_CREATEBREAKSRC         32874
#define IDM_UNIT_ATTRIB_ADD_CHAIN       32876
#define ID_FILE_RUN_WORLD               32882
#define ID_EDIT_GAME_SCENARIO           32884
#define ID_VIEW_BREAKSOURCE             32885
#define ID_EDIT_REBUILDWORLD            32888
#define ID_VIEW_SETTINGS                32891
#define ID_EDIT_EFFECTS                 32893
#define ID_MENU_COPY                    32895
#define ID_MENU_PASTE                   32896
#define ID_FILE_RUN_MENU                32897
#define ID_IDR                          32899
#define IDM_UNIT_TYPE_ADD_UNIT          32902
#define ID_DEBUG_SAVEDICTIONARY         32905
#define ID_EDIT_TOOLZERS                32906
#define ID_EDIT_PREFERENCES             32907
#define ID_FILE_PROPERTIES              32908
#define ID_TOOLS                        32909
#define ID_EDIT_VOICES                  32914
#define ID_FILE_EXPORTVISTAENGINE       32915
#define ID_VIEW_TOOL_PREVIEW            32921
#define ID_DEBUG_SHOWPALETTETEXTURE     32922
#define ID_POPUP_CREATEICE              32923
#define ID_POPUP_                       32924
#define ID_POPUP_CREATEICEERASER        32925
#define ID_POPUP_CREATEZONE             32926
#define ID_POP_ADDCOLORPIC              32929
#define ID_EDIT_HEADS                   32930
#define ID_EDIT_SOUND_TRACKS            32934
#define ID_POPUP_CREATEEFFECT           32934
#define ID_EDIT_REELS                   32941
#define ID_POPUP_CREATEGEOWAVESRC       32945
#define IDM_POINTER_DELETE              40007
#define IDM_FIRST_DYNAMIC_MENU          40011
#define IDM_LAST_DYNAMIC_MENU           40111
#define ID_VIEW_CAMERAS                 40112
#define ID_VIEW_EFFECTS                 40113
#define ID_VIEW_GRADIENTS_WINDOW        40116
#define ID_POPUP_DE                     40117
#define IDM_WEAPON_PRM_DELETE           40120
#define ID_POPUP_CREATE                 40121
#define ID_POPUP_CREATE_FIRST_DYNAMIC   40122
#define ID_POPUP_CREATE_LAST_DYNAMIC    40222
#define ID_EDIT_PARAMETER_TABLE         40223
#define ID_EDIT_EFFECTS_EDITOR          40224
#define ID_EDIT_TERTOOLS                40235
#define ID_POP_SORT                     40236
#define ID_EDIT_CURSORS                 40237
#define ID_POPUP_TYPE                   40239
#define IDM_TYPE_FIRST_ITEM             40240
#define IDM_TYPE_EDIT                   40241
#define ID_EDIT_DEFAULT_ANIMATION_CHAINS 40242
#define ID_DEBUG_EDIT_DEBUG_PRM         40244
#define ID_DEBUG_EDIT_AUX_ATTRIBUTE     40246
#define ID_DEBUG_EDIT_RIGID_BODY_PRM    40249
#define ID_DEBUG_EDIT_TOOLZER           40252
#define ID_DEBUG_EDIT_EXPLODE_TABLE     40254
#define ID_DEBUG_SHOWMIPMAP             40256
#define ID_DEBUG_EDIT_SOURCES_LIBRARY   40257
#define IDM_PROJECTILE_ADD              40259
#define IDM_DELETE                      40260
#define IDM_ADD                         40262
#define ID_POP_PROPERTIES               40263
#define ID_Menu40264                    40264
#define ID_EDIT_CHANGETOTALWORLDHEIGHT  40265
#define ID_VIEW_SHOW_GRID               40267
#define IDM_SORT_BY_TIME                40269
#define IDM_SORT_BY_NAME                40270
#define ID_VIEW_MENUBAR                 40271
#define ID_TOOL_FIRST                   40276
#define ID_TOOL_SELECT                  40276
#define ID_TOOL_MOVE                    40277
#define ID_TOOL_ROTATE                  40278
#define ID_TOOL_SCALE                   40279
#define ID_TOOL_LAST                    40279
#define ID_VIEW_GEOSURFACE              40282
#define ID_Menu40283                    40283
#define ID_ZZZ_PASTE                    40286
#define ID_FILE_STATISTICS              40288
#define ID_VIEW_ENABLE_TIME_FLOW        40292
#define IDM_MOVE_UP                     40295
#define IDM_MOVE_DOWN                   40296
#define ID_FILE_EXPORTTEXTTOEXCEL       40297
#define ID_FILE_IMPORTTEXTFROMEXCEL     40298
#define ID_DEBUG_EDITSTRATEGY           40299
#define IDM_FOLLOW_REFERENCE            40302
#define IDM_CLEAR_CONTENT               40303
#define IDM_EDIT                        40307
#define IDM_PASTE                       40308
#define IDM_COPY                        40309
#define ID_ZZZ_IMPORT                   40312
#define ID_ZZZ_EXPORT40313              40313
#define IDM_EXPORT_FULL                 40316
#define IDM_IMPORT_FULL                 40317
#define IDM_EXPORT_GROUP_TYPE           40318
#define IDM_IMPORT_GROUP_TYPE           40319
#define ID_DEBUG_UI_SPRITE_LIB          40321
#define ID_VIEW_OBJECTS_MANAGER         40323
#define IDM_SELECT_TAB                  40328
#define IDM_DESELECT_OTHERS             40329
#define IDM_DESELECT_TAB                40330
#define IDM_LOCATE                      40332
#define ID_Menu40334                    40334
#define ID_VIEW_TIME_SLIDER             40335
#define IDM_MENU_COPYCHAINS             40338
#define IDM_COPY_CHAINS                 40340
#define IDM_PASTE_CHAINS                40341
#define ID_LIBRARIES_UI_MESSAGES        40345
#define ID_EDITORS_EXPORTPARAMETERS     40346
#define ID_EDITORS_IMPORTPARAMETERS     40347
#define ID_EXPORT_PARAMETERS            40349
#define ID_IMPORT_PARAMETERS            40350
#define ID_FILE_SAVEWITHOUTTERTOOLCOLOR 40351
#define ID_TEXT_SPRITES                 40352
#define ID_LIBRARIES_UI_MESSAGE_TYPE    40353
#define ID_VIEW_HIDE_MODELS             40354
#define ID_FILE_MERGE                   40355
#define ID_Menu                         40356
#define ID_VIEW_PATH_FINDING            40358
#define ID_FILE_SAVEVOICEFILEDURATIONS  40359
#define ID_VIEW_PATH_FINDING_SELECT_REFERENCE 40360
#define ID_EDIT_UPDATE_SURFACE          40362
#define ID_DEBUG_IMPORTOVERRIDEN        40364
#define ID_DEBUG_EXPORT_PARAMETER_TREE  40365
#define ID_DEBUG_IMPORT_PARAMETER_TREE  40367
#define ID_Menu40368                    40368
#define ID_FILE_IMPORTPARAMETERESFROMEXCEL 40369
#define ID_FILE_EXPORTPARAMETERS        40370
#define ID_FILE_PARAMETERS_IMPORT_FULL  40375
#define ID_FILE_PARAMETERS_IMPORT_BY_GROUPS 40376
#define ID_FILE_PARAMETERS_EXPORT_FULL  40377
#define ID_FILE_PARAMETERS_EXPORT_BY_GROUPS 40378
#define ID_DEBUG_EDIT_ZIP_CONFIG        40379
#define ID_FILE_PARAMETERS_EXPORT_UNITS 40381
#define ID_FILE_PARAMETERS_IMPORT_UNITS 40382
#define ID_EDIT_SAVE_CAMERA_AS_DEFAULT  40386
#define ID_EXPORTPARAMETERSTOEXCEL_STATISTICS 40387
#define ID_FILE_PARAMETERS_EXPORT_STATISTICS 40388
#define ID_HELP_KEY_INFO                40392
#define ID_FILE_RESAVE_WORLDS           40395
#define ID_FILE_RESAVE_TRIGGERS         40396
#define ID_FILE_UPDATE_QUICK_START_WORLDS_LIST 40398
#define ID_LIBRARIES_COMMANDCOLORS      40399
#define ID_FILE_EXIMWORLD               40401
#define ID_LIBRARIES_UI_SHOW_MODE_SPRITES 40403
#define ID_VIEW_SHOW_CAMERA_BORDERS     40405
#define ID_LIBRARIES_TERRRAINTYPENAME   40406
#define ID_EDIT_MAPPRESET               40407
#define ID_EDIT_ROLLINGBORDER           40408

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         40409
#define _APS_NEXT_CONTROL_VALUE         1311
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
