//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UIEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_UI_ABOUTBOX                 100
#define IDR_HTML_SNAPOPTIONSDLG         103
#define IDR_MAINFRAME                   128
#define IDR_UIEditorTYPE                129
#define IDC_NODROP                      130
#define IDD_ATTRIB_EDITOR               130
#define IDC_POINTER_COPY                131
#define IDR_UIEDITORFRAME               135
#define IDB_BITMAP1                     135
#define IDS_NAME_COLUMN                 136
#define IDS_VALUE_COLUMN                137
#define IDS_TYPE_COLUMN                 138
#define IDC_VECTOR_NODE_ADD_ELEMENT     139
#define IDC_EDIT_NODE_VECTOR_ELEMENT_INSERT_BEFORE 140
#define IDC_FPOINT                      140
#define IDC_EDIT_NODE_VECTOR_ELEMENT_REMOVE 141
#define IDC_POINTER                     141
#define IDS_REMOVE_ITEM                 142
#define IDC_SPLITTER                    142
#define IDS_ERROR_IN_CUSTOM_VALUE       143
#define IDC_APPLY_BUTTON                144
#define IDS_APPLY_BUTTON                144
#define IDB_CONTROLS_TREE               144
#define IDC_CANCEL_BUTTON               145
#define IDS_STRING145                   145
#define IDS_CANCEL_BUTTON               145
#define IDD_UI_TEXTURE_EDITOR_DLG       145
#define IDD_UI_SPRITE_EDITOR_DLG        145
#define IDS_FALSE                       146
#define IDB_ATTRIB_EDITOR_CTRL          146
#define IDR_CONTROL_MENU                146
#define IDS_TRUE                        147
#define IDD_ADD_CONTROL                 147
#define IDR_ELEMENT_MENU                147
#define IDS_NOITEMSEL                   148
#define IDS_SELFORINFO                  149
#define IDR_STATE_MENU                  150
#define IDR_CONTROLS_MENU               151
#define IDI_ICON1                       153
#define IDB_SPLASH                      155
#define IDD_DLG_FORMATION_EDITOR        176
#define IDR_FORMATION_CELL_MENU         177
#define IDD_DLG_FORMULA_EDITOR          179
#define IDD_GRADIENT_EDITOR             204
#define IDC_TREE_CTRL                   1000
#define IDC_ATTRIB_EDITOR               1000
#define IDC_HORIZONTAL_LINE             1001
#define IDC_COMBO1                      1002
#define IDC_COORD_LEFT_EDIT             1002
#define IDC_COORD_TOP_EDIT              1003
#define IDC_COORD_WIDTH_EDIT            1004
#define IDC_COORD_HEIGHT_EDIT           1005
#define IDC_VIEW                        1006
#define IDC_NEXT_BUTTON                 1006
#define IDC_COORD_LABEL                 1007
#define IDC_COORD_COMMA_LABEL           1008
#define IDC_COORD_X_LABEL               1009
#define IDC_LOWER_LINE                  1010
#define IDC_SATURATION_EDIT             1010
#define IDC_UPPER_LINE                  1011
#define IDC_V_LINE                      1011
#define IDC_SELECT_TEXTURE_BUTTON       1012
#define IDC_TEXTURE_ADD_BUTTON          1012
#define IDC_TEXTURES_COMBO              1013
#define IDC_TEXTURE_SIZE_LABEL          1014
#define IDR_FORMATION_MENU              1014
#define IDC_TYPE_COMBO                  1015
#define IDC_TEXTURE_REMOVE_BUTTON       1015
#define IDC_GRADIENT_EDITOR             1016
#define IDC_H_LINE1                     1016
#define IDC_R_SLIDER                    1017
#define IDC_H_LINE2                     1017
#define IDC_G_SLIDER                    1018
#define IDC_H_LINE3                     1018
#define IDC_A_SLIDER                    1019
#define IDC_TEXTURE_LOC_ADD_BUTTON      1019
#define IDC_B_SLIDER                    1020
#define IDC_R_EDIT                      1022
#define IDC_G_EDIT                      1023
#define IDC_B_EDIT                      1024
#define IDC_A_EDIT                      1025
#define IDC_SOLID_COLOR                 1026
#define IDC_POSITION_EDIT               1027
#define IDC_GRID_SIZE_EDIT              1028
#define IDC_GRID_XSIZE_EDIT             1028
#define IDC_CHECK1                      1029
#define IDC_SNAP_TO_GRID_CHECK          1029
#define IDC_PLAY_CHECK                  1029
#define IDC_SHOW_GRID_CHECK             1030
#define IDC_STATUS_LABEL                1030
#define IDC_LARGE_GRID_SIZE_EDIT        1031
#define IDC_LARGE_GRID_XSIZE_EDIT       1031
#define IDC_GRID_YSIZE_EDIT             1032
#define IDC_NEXT_FRAME                  1032
#define IDC_LARGE_GRID_YSIZE_EDIT       1033
#define IDC_PREV_FRAME                  1033
#define IDC_BACKGROUND_COLOR            1034
#define IDC_SATURATION_SLIDER           1035
#define IDC_DIFFUSE_COLOR               1036
#define IDC_DIFFUSE_COLOR_LABEL         1037
#define IDC_SATURATION_LABEL            1038
#define IDC_TEXTURE_LABEL               1039
#define IDC_NAME_EDIT                   1054
#define IDC_CYCLED_CHECK                1089
#define IDC_PEG_LABEL                   1090
#define IDC_PREV_BUTTON                 1091
#define IDC_HLINE                       1094
#define IDC_FORMATION_EDITOR            1117
#define IDC_H_LINE                      1118
#define IDC_TYPES_BUTTON                1119
#define IDC_FORMULA_EDIT                1124
#define IDC_RESULT_LABEL                1125
#define IDC_INSERT_BUTTON               1126
#define IDC_CONDITION_LIST              1137
#define IDC_FILTER_EDIT                 1213
#define IDC_TREE_CONTROL                1216
#define IDC_FILTER_LABEL                1217
#define IDC_MARK_FIRST                  1262
#define IDC_MARK_SECOND                 1263
#define IDC_MARK_THIRD                  1264
#define IDC_MARK_FOURTH                 1265
#define IDC_A_LABEL                     1275
#define IDC_CONDITION_EDITOR            2001
#define IDD_CONDITION_EDITOR            2012
#define IDD_TREE_SELECTOR               2022
#define IDD_DLG_HOTKEY_SELECTOR         2023
#define IDB_TREELIST_BITMAP             8000
#define IDC_CURSOR_SIZE                 8002
#define IDB_TREELIST_CHECK              8003
#define IDB_TREELIST_LOCK               8004
#define IDC_CURSOR_BUTTON               8005
#define IDC_CURSOR_CHECK                8006
#define IDC_CURSOR_LOCK                 8007
#define IDB_TREELIST_TREE               8008
#define IDB_TREELIST_SORT               8009
#define IDB_TREELIST_HEADER             8010
#define IDB_TREELIST_DISABLE            8011
#define IDC_CURSOR_VERT                 8012
#define IDC_CURSOR_HORZ                 8013
#define IDB_CONTROLS_TREE_OLD           8013
#define IDC_CURSOR_CROSS                8014
#define IDC_CURSOR_DROP                 8015
#define IDC_CURSOR_STOP                 8016
#define IDC_CURSOR_SPLIT                8017
#define ID_UI_EDIT_TREE                 32771
#define ID_UI_HELP_ABOUT                32772
#define ID_BUTTON32773                  32773
#define IDC_INSERT_BEFORE               32775
#define IDC_REMOVE                      32776
#define ID_UI_FILE_SAVE                 32776
#define ID_DD                           32777
#define ID_UI_EDIT_DELETE               32778
#define IDC_EXTENSIBLE_NODE_ADD_ELEMENT 32779
#define ID_CLEAR_POLYMORFIC             32780
#define ID_UI_FILE_QUICK_SAVE           32781
#define ID_CHOOSE_COLOR                 32782
#define ID_COLLAPSE_ALL_SUBITEMS        32784
#define ID_UI_EDIT_ADD                  32784
#define ID_EXPAND_ALL_SUBITEMS          32785
#define IDM_ADD_ELEMENT                 32787
#define ID_POPUP_DELETE                 32787
#define IDM_CLEAR_CONTAINER             32788
#define IDM_DELETE                      32791
#define IDM_ADD_CONTROL_FIRST           32793
#define IDM_ADD_CONTROL_LAST            32893
#define ID_UI_EDIT_ADD_SCREEN           32894
#define ID_UI_EDIT_DELETE_SCREEN        32895
#define ID_EDIT_FONT_LIBRARY            32904
#define IDM_ADD_STATE                   32906
#define ID_UI_EDIT_FONT_LIBRARY         32907
#define IDM_ADD_SCREEN                  32913
#define ID_UI_EDIT_TEST                 32914
#define ID_UI_FILE_OPEN                 32916
#define ID_EDIT_SNAP_OPTIONS            32917
#define ID_BUTTON32817                  32918
#define ID_UI_EDIT_SNAP_OPTIONS         32918
#define ID_UI_EDIT_UNDO                 32919
#define ID_UI_VIEW_SHOW_GRID            32923
#define ID_UI_VIEW_SNAP_TO_GRID         32926
#define IDM_CONTROL_DUPLICATE           32929
#define IDM_REMOVE_ELEMENT              32946
#define IDM_INSERT_ELEMENT_BEFORE       32954
#define ID_UI_EDIT_PARAMETERS           32956
#define ID_UI_VIEW_SHOW_BORDER          32957
#define ID_UI_VIEW_SNAP_TO_BORDER       32958
#define ID_UI_VIEW_SHOW_GUIDES          32959
#define ID_UI_VIEW_SNAP_TO_GUIDES       32960
#define IDM_SORT                        32962
#define IDM_MOVE_UP                     32965
#define IDM_MOVE_DOWN                   32966
#define ID_UI_EDIT_TO_TEXTURE_SIZE      32967
#define ID_UI_VIEW_ZOOM_ONE_TO_ONE      32970
#define ID_UI_VIEW_ZOOM_BY_WIDTH        32971
#define ID_VIEW_ZOOM                    32972
#define ID_UI_VIEW_SHOWHOTKEYS          32980
#define IDM_POINTER_DELETE              40007
#define IDM_FIRST_DYNAMIC_MENU          40011
#define IDM_LAST_DYNAMIC_MENU           40111
#define IDM_TYPE_FIRST_ITEM             40240
#define IDM_FOLLOW_REFERENCE            40302
#define IDM_CLEAR_CONTENT               40303
#define IDM_EDIT                        40307
#define IDM_PASTE                       40308
#define IDM_COPY                        40309

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32981
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
