#ifndef _RENDERSTATES_H_
#define _RENDERSTATES_H_

enum DX_TEXTUREADDRESS { //см. D3DTEXTUREADDRESS
    DX_TADDRESS_WRAP = 1,
    DX_TADDRESS_MIRROR = 2,
    DX_TADDRESS_CLAMP = 3,
    DX_TADDRESS_BORDER = 4,
    DX_TADDRESS_MIRRORONCE = 5,
};

enum DX_TEXTUREFILTERTYPE {
    DX_TEXF_NONE = 0,
    DX_TEXF_POINT = 1,
    DX_TEXF_LINEAR = 2,
    DX_TEXF_ANISOTROPIC = 3,
    DX_TEXF_PYRAMIDALQUAD = 6,
    DX_TEXF_GAUSSIANQUAD = 7,
};

union SAMPLER_DATA
{
	struct {
		DWORD addressu:3;//D3DSAMP_ADDRESSU
		DWORD addressv:3;//D3DSAMP_ADDRESSV
		DWORD addressw:3;//D3DSAMP_ADDRESSW
		DWORD minfilter:3;//D3DSAMP_MINFILTER
		DWORD magfilter:3;//D3DSAMP_MAGFILTER
		DWORD mipfilter:3;//D3DSAMP_MIPFILTER
		DWORD :14;
		
		DWORD bordercolor;//D3DSAMP_BORDERCOLOR
	};
	
	DWORD dword[2];
};

#endif _RENDERSTATES_H_
