#ifndef __N_PARTICLE_ID_H_INCLUDED__
#define __N_PARTICLE_ID_H_INCLUDED__
//типы блоков в .effect файле
const int IDS_EMITTERLIST			=1;
const int IDS_EMITTERLIST_HEAD		=2;
const int IDS_EMITTER				=10;
const int IDS_EMITTERHEAD			=11;
const int IDS_EMITTER_LIFE_TIME		=12;
const int IDS_EMITTER_LIFE_TIME_DELTA=13;
const int IDS_EMITTER_SIZE			=14;
const int IDS_EMITTER_SIZE_DELTA	=15;
const int IDS_EMITTER_NUM_PARTICLE	=16;
const int IDS_EMITTER_VELOCITY_DELTA=17;
const int IDS_EMITTER_PARTICLE_POSITION=18;

const int IDS_BUILDKEY_Z				=98;
const int IDS_BUILDKEY_SPL				=99;
const int IDS_BUILDKEY_INT				=100;
const int IDS_BUILDKEY_HEADER			=101;
const int IDS_BUILDKEY_PARTICLE_POS		=102;
const int IDS_BUILDKEY_LIFE_TIME		=103;
const int IDS_BUILDKEY_LIFE_TIME_DELTA	=104;
const int IDS_BUILDKEY_BEGIN_SIZE		=105;
const int IDS_BUILDKEY_BEGIN_SIZE_DELTA	=106;
const int IDS_BUILDKEY_NUM_PARTICLE		=107;
const int IDS_BUILDKEY_VELOCITY_DELTA	=108;
const int IDS_BUILDKEY_BEGIN_SPEED		=109;
const int IDS_BUILDKEY_POSITION			=110;
const int IDS_BUILDKEY_ROTATION			=111;
const int IDS_BUILDKEY_INT_LIGHT		=112;
const int IDS_BUILDKEY_BEGIN_POSITION   =113;
const int IDS_BUILDKEY_PLUME			=114;
const int IDS_BUILDKEY_OTHER_NAME		=115;
const int IDS_BUILDKEY_WIND				=116;
const int IDS_BUILDKEY_VEL_NOISE		=117;
const int IDS_BUILDKEY_DIR_NOISE		=118;
const int IDS_BUILDKEY_EMITTER_SCALE	=119;
const int IDS_BUILDKEY_VEL_OCTAVES		=120;
const int IDS_BUILDKEY_DIR_OCTAVES		=121;
const int IDS_BUILDKEY_DIR_ANGLE_BY_CENTER	=122;
const int IDS_BUILDKEY_ORIENTATION		=123;

const int IDS_BUILDKEY_VELOCITY			=150;	
const int IDS_BUILDKEY_SIZE				=151;
const int IDS_BUILDKEY_COLOR			=152;
const int IDS_BUILDKEY_ALPHA			=153;
const int IDS_BUILDKEY_ANGLE_VELOCITY	=154;
const int IDS_BUILDKEY_GRAVITY			=155;
const int IDS_BUILDKEY_NORMAL_POSITION  =156;
const int IDS_BUILDKEY_RANDOM_TEXTURES  =157;
const int IDS_BUILDKEY_PLANAR_TURN		=158;

const int IDS_EFFECTKEY					=200;
const int IDS_EFFECTKEY_HEADER			=201;

const int IDS_BUILDKEY_SPL_POSITION		=300;
const int IDS_BUILDKEY_SPL_HEADER		=301;
const int IDS_BUILDKEY_SPL_DIRECTION	=310;

const int IDS_BUILDKEY_ZEMITTER			=400;

const int IDS_BUILDKEY_LIGHT			=500;
const int IDS_BUILDKEY_LIGHT_HEAD		=501;
const int IDS_BUILDKEY_TEMPLATE_DATA    =502;

const int IDS_BUILDKEY_COLUMN_LIGHT		=600;
const int IDS_BUILDKEY_COLUMN_LIGHT_HEAD=601;


const int IDS_BUILDKEY_COLUMN_LIGHT_U_VEL	= 610;
const int IDS_BUILDKEY_COLUMN_LIGHT_V_VEL	= 612;
const int IDS_BUILDKEY_SIZE2				= 613;
const int IDS_BUILDKEY_COLUMN_LIGHT_HEIGHT	= 614;
const int IDS_BUILDKEY_COLUMN_LIGHT_ROT		= 615;
const int IDS_BUILDKEY_COLUMN_LIGHT_LENGTH	= 616;

const int IDS_BUILDKEY_LIGHTING				=700;
const int IDS_BUILDKEY_LIGHTING_HEADER		=701;
const int IDS_BUILDKEY_LIGHTING_PARAMETERS	=702;
const int IDS_BUILDKEY_LIGHTING_POSITIONS	=703;

#endif
