add_library(kdWidgets STATIC
    Application.cpp
    Box.cpp
    Button.cpp
    CheckBox.cpp
    CheckComboBox.cpp
    Clipboard.cpp
    ColorChooser.cpp
    ColorChooserDialog.cpp
    ColorRamp.cpp
    ColorRect.cpp
    ComboBox.cpp
    CommandManager.cpp
    ConstStringList.cpp
    ContentUtil.cpp
    CurveEditor.cpp
    Dialog.cpp
    DragManager.cpp
    EditorDialog.cpp
    Entry.cpp
    FileDialog.cpp
    Frame.cpp
    GradientBar.cpp
    GradientDialog.cpp
    HLine.cpp
    HotkeyButton.cpp
    HotkeyContext.cpp
    HotkeyDialog.cpp
    ImageStore.cpp
    Label.cpp
    LibraryEditor.cpp
    LibraryTab.cpp
    LibraryTree.cpp
    MenuBar.cpp
    Navigator.cpp
    ObjectsTree.cpp
    PlugDialog.cpp
    PopupMenu.cpp
    ProgressBar.cpp
    PropertyEditor.cpp
    PropertyIArchive.cpp
    PropertyOArchive.cpp
    PropertyRow.cpp
    PropertyRowColor.cpp
    PropertyRowComboListColor.cpp
    PropertyRowDecorators.cpp
    PropertyRowFileSelector.cpp
    PropertyRowGradient.cpp
    PropertyRowHotkey.cpp
    PropertyRowRanged.cpp
    PropertyTree.cpp
    RadioButton.cpp
    RadioButtonBox.cpp
    Sandbox.cpp
    ScrolledWindow.cpp
    Slider.cpp
    Splitter.cpp
    StdAfx.cpp
    Tabs.cpp
    Timer.cpp
    Tool.cpp
    Toolbar.cpp
    Tooltip.cpp
    Tree.cpp
    TreeSelector.cpp
    Viewport.cpp
    Viewport2D.cpp
    Widget.cpp
    Win32Proxy.cpp
    Win32/Drawing.cpp
    Win32/MemoryDC.cpp
    Win32/MessageLoop.cpp
    Win32/Window.cpp
    Window.cpp
    Workspace.cpp
    _WidgetWindow.cpp
    _WidgetWithWindow.cpp
)

target_include_directories(kdWidgets PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(kdWidgets PUBLIC EngineIncludes Serialization XMath)
