#ifndef __NETCOMMANDBASE_H__
#define __NETCOMMANDBASE_H__

enum NCEventID
{
	NETCOM_ID_NONE=0,


	NETCOM_4C_ID_START_LOAD_GAME,

	NETCOM_4G_ID_UNIT_COMMAND,
	NETCOM_4G_ID_UNIT_LIST_COMMAND,
	NETCOM_4G_ID_PLAYER_COMMAND,
	NETCOM_4G_ID_EVENT,
	NETCOM_4G_ID_FORCED_DEFEAT,

	NETCOM_4G_ID_CHAT_MESSAGE,

	NETCOM_4H_ID_BACK_GAME_INFORMATION,
	NETCOM_4C_ID_DISPLAY_DISTRINC_AREAS,
	NETCOM_4C_ID_SAVE_LOG,
	NETCOM_4C_ID_SEND_LOG_2_HOST,

	NETCOM_4H_ID_BACK_GAME_INFORMATION_2,


	NETCOM_4H_ID_REQUEST_PAUSE,
	NETCOM_4C_ID_PAUSE,

	NETCOM_ID_NEXT_QUANT,

	////---
	NETCOM_4H_ID_JOIN_REQUEST,
	NETCOM_4C_ID_JOIN_RESPONSE,

	NETCOM_4H_ID_REJOIN_REQUEST,
	NETCOM_4C_ID_REJOIN_RESPONCE,
	NETCOM_4C_ID_REQUEST_LAST_QUANTS_COMMANDS,
	NETCOM_4H_ID_RESPONCE_LAST_QUANTS_COMMANDS,
	//NETCOM_4C_ID_REJOIN_RESPONSE,

	NETCOMC_ID_PLAYER_READY,
	NETCOM_ID_START_GAME,
	NETCOM_4C_ID_CONTINUE_GAME_AFTER_HOST_MIGRATE,

	NETCOM_4C_ID_CUR_MISSION_DESCRIPTION_INFO,
	NETCOM_4H_ID_CHANGE_PLAYER_RACE,
	NETCOM_4H_ID_CHANGE_PLAYER_COLOR,
	NETCOM_4H_ID_CHANGE_PLAYER_SIGN,
	NETCOM_4H_ID_CHANGE_REAL_PLAYER_TYPE,
	NETCOM_4H_ID_CHANGE_PLAYER_DIFFICULTY,
	NETCOM_4H_ID_CHANGE_PLAYER_CLAN,
	//NETCOM_4H_ID_CHANGE_MAP,
	NETCOM_4H_ID_CHANGE_MISSION_DESCRIPTION,
	NETCOM_4H_ID_JOIN_2_COMMAND,
	NETCOM_4H_ID_KICK_IN_COMMAND,
	NETCOM_4C_ID_DISCARD_USER,

	NETCOM_4H_ID_START_LOAD_GAME,

	EVENT_ID_CREATE_GAME,
	NETCOM_4H_ID_CREATE_GAME,

	NETCOM_4C_ID_ALIFE_PACKET,
	NETCOM_4H_ID_ALIFE_PACKET,

	NETCOM_4C_ID_CLIENT_IS_NOT_RESPONCE,

	EVENT_ID_SERVER_TIME_CONTROL,
};

//-------------------------------

struct NetCommandBase
{
	NCEventID EventID;

	NetCommandBase(NCEventID event_id) { EventID = event_id; }
	virtual ~NetCommandBase() {}

	virtual void Write(XBuffer& out) const {}

	virtual bool isGameCommand() const { return false; }
};

#endif //__NETCOMMANDBASE_H__