#pragma once
#ifndef __VISTARPC_RPC_ENUMS_H_INCLUDED__
#define __VISTARPC_RPC_ENUMS_H_INCLUDED__

enum OperationStatus
{
	STATUS_GOOD,
	STATUS_BAD_USER_OR_PASSWORD,
	STATUS_USER_NAME_EXIST,
	STATUS_DOUBLE_OR_NOT_LOGON,
	STATUS_OTHER_ERROR
};

#endif //__VISTARPC_RPC_ENUMS_H_INCLUDED__