#ifndef __DIRECT_CONTROL_MODE_H__
#define __DIRECT_CONTROL_MODE_H__

enum DirectControlMode
{
	DIRECT_CONTROL_DISABLED = 0,
	DIRECT_CONTROL_ENABLED = 1,
	SYNDICATE_CONTROL_ENABLED = 2
};

#endif // __DIRECT_CONTROL_MODE_H__