# Compile a set of HLSL sources to the platform's native SDL_GPU shader
# format and stitch the resulting bytes into one C++ header.
#
#   Windows : DXIL  via the Windows SDK's dxc.exe
#   Linux   : SPIRV via SDL_shadercross
#   macOS   : MSL   via SDL_shadercross
#
# Only the host backend's format is ever produced: the runtime consumes
# exactly one, picked at compile time in SDLShaders/ShaderBlob.h. Each
# entry contributes a `<var>_blob[]` / `<var>_blob_len` pair; the format
# is implicit in the platform, so the header carries no format tag.
#
# Compiling and embedding live in one script (rather than two custom
# commands glued by DEPENDS) so a parallel build can never schedule the
# embed ahead of the compile that feeds it.
#
# Invoked at build time by the shader rules in Render/CMakeLists.txt:
#   cmake -DOUT_HEADER=... -DMODE=<dxc|shadercross> -DCOMPILER=<exe>
#         -DFORMAT_EXT=<dxil|spv|msl> -DSRC_DIR=... -DGEN_DIR=...
#         -DENTRIES="var1=file1.hlsl:stage1[:DEF=1,DEF2]|var2=..."
#         -P bin2h.cmake
#
# Inputs:
#   OUT_HEADER : output .h path
#   MODE       : "dxc" (Windows SDK dxc.exe) or "shadercross"
#   COMPILER   : full path to the compiler executable
#   FORMAT_EXT : artifact extension — dxil / spv / msl
#   SRC_DIR    : directory the .hlsl sources are resolved against
#   GEN_DIR    : directory intermediates land in
#   ENTRIES    : '|'-separated list of "var=source.hlsl:stage[:DEFS]".
#                NOT ';'-separated: CMake flattens semicolons inside a
#                COMMAND argument into separate argv entries, so only the
#                first entry would survive the trip into this script.
#                DEFS is comma-separated; each becomes one -D argument.
#
# Every entry point in this codebase's HLSL is named `main`, so the entry
# name is not part of the spec.

if(NOT OUT_HEADER OR NOT MODE OR NOT COMPILER OR NOT FORMAT_EXT
   OR NOT SRC_DIR OR NOT GEN_DIR OR NOT ENTRIES)
    message(FATAL_ERROR
        "bin2h.cmake: requires OUT_HEADER, MODE, COMPILER, FORMAT_EXT, "
        "SRC_DIR, GEN_DIR, ENTRIES")
endif()

file(MAKE_DIRECTORY "${GEN_DIR}")

set(_BODY "// Auto-generated by cmake/bin2h.cmake. Do not edit.\n#pragma once\n\n")

# Compile one entry point of one source to PATH. DEFINES_LIST is a CMake
# list of `NAME` / `NAME=VAL` strings.
#
# `-D<name>` must be one concatenated argument: shadercross parses its
# argv itself and rejects a separated `-D NAME` as an unknown argument.
# dxc accepts the concatenated form too, so both modes spell it the same.
function(_run_compile PATH HLSL STAGE DEFINES_LIST)
    set(_defines_args)
    foreach(_d IN LISTS DEFINES_LIST)
        if(NOT _d STREQUAL "")
            list(APPEND _defines_args "-D${_d}")
        endif()
    endforeach()

    if(MODE STREQUAL "dxc")
        # SDL_GPU requires DXIL at Shader Model 6.0 or newer.
        if(STAGE STREQUAL "vertex")
            set(_profile "vs_6_0")
        elseif(STAGE STREQUAL "fragment")
            set(_profile "ps_6_0")
        elseif(STAGE STREQUAL "compute")
            set(_profile "cs_6_0")
        else()
            message(FATAL_ERROR "bin2h.cmake: unknown stage '${STAGE}'")
        endif()
        execute_process(
            COMMAND "${COMPILER}"
                -nologo
                -T "${_profile}"
                -E main
                ${_defines_args}
                -Fo "${PATH}"
                "${HLSL}"
            RESULT_VARIABLE _rc
            OUTPUT_VARIABLE _stdout
            ERROR_VARIABLE  _stderr
        )
    elseif(MODE STREQUAL "shadercross")
        if(FORMAT_EXT STREQUAL "spv")
            set(_fmt_tag "SPIRV")
        elseif(FORMAT_EXT STREQUAL "msl")
            set(_fmt_tag "MSL")
        elseif(FORMAT_EXT STREQUAL "dxil")
            set(_fmt_tag "DXIL")
        else()
            message(FATAL_ERROR "bin2h.cmake: unknown FORMAT_EXT '${FORMAT_EXT}'")
        endif()
        execute_process(
            COMMAND "${COMPILER}"
                "${HLSL}"
                -s HLSL
                -d "${_fmt_tag}"
                -t "${STAGE}"
                -e main
                ${_defines_args}
                -o "${PATH}"
            RESULT_VARIABLE _rc
            OUTPUT_VARIABLE _stdout
            ERROR_VARIABLE  _stderr
        )
    else()
        message(FATAL_ERROR "bin2h.cmake: unknown MODE '${MODE}'")
    endif()

    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR
            "${MODE} failed for ${HLSL} (${STAGE}, ${FORMAT_EXT}):\n"
            "  exit=${_rc}\n"
            "  stdout=${_stdout}\n"
            "  stderr=${_stderr}")
    endif()
endfunction()

# Emit the (array, length) pair for one compiled artifact.
function(_emit_one VAR PATH)
    file(READ "${PATH}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _bytelen "${_hexlen} / 2")
    # One regex pass beats iterating byte-by-byte in CMake script.
    string(REGEX REPLACE "(..)" "0x\\1,\n" _bytes "${_hex}")
    # Append each piece as its own quoted literal. Routing them through an
    # intermediate variable would make CMake treat the text as a list and
    # split it on the `;` that terminates every declaration below.
    string(APPEND _BODY "static const unsigned char ${VAR}_blob[] = {\n${_bytes}};\n")
    string(APPEND _BODY "static const unsigned int  ${VAR}_blob_len = ${_bytelen};\n\n")
    set(_BODY "${_BODY}" PARENT_SCOPE)
endfunction()

string(REPLACE "|" ";" _entries_list "${ENTRIES}")

foreach(_entry IN LISTS _entries_list)
    # Split on the *first* `=` only: the defines that follow carry their own, as in
    # "water_vert=water.vert.hlsl:vertex:REFLECTION=0".
    if(NOT _entry MATCHES "^([^=]+)=(.+)$")
        message(FATAL_ERROR
            "bin2h.cmake: bad entry '${_entry}' (want 'var=source.hlsl:stage[:DEFS]')")
    endif()
    set(_var  "${CMAKE_MATCH_1}")
    set(_spec "${CMAKE_MATCH_2}")

    string(REPLACE ":" ";" _spec_parts "${_spec}")
    list(LENGTH _spec_parts _ns)
    if(_ns LESS 2 OR _ns GREATER 3)
        message(FATAL_ERROR
            "bin2h.cmake: bad spec '${_spec}' in '${_entry}' (want source.hlsl:stage[:DEFS])")
    endif()
    list(GET _spec_parts 0 _src)
    list(GET _spec_parts 1 _stage)
    set(_defs "")
    if(_ns EQUAL 3)
        list(GET _spec_parts 2 _defs_csv)
        string(REPLACE "," ";" _defs "${_defs_csv}")
    endif()

    set(_artifact "${GEN_DIR}/${_var}.${FORMAT_EXT}")
    _run_compile("${_artifact}" "${SRC_DIR}/${_src}" "${_stage}" "${_defs}")
    _emit_one("${_var}" "${_artifact}")
endforeach()

file(WRITE "${OUT_HEADER}" "${_BODY}")
